test(external-volumes): add external volumes test suite
Adds a test case that creates an app with external volume and
tests to see that it is persistent after suspension and resume.
Also, moves the external volume tests from the other test
suites into this newly created one. There is also automatic cleanup
of external volumes via a script that runs during the teardown phase.

Closes DCOS-15073

diff --git a/system-tests/services/_scripts/external-volumes/setup b/system-tests/services/_scripts/external-volumes/setup
--- a/system-tests/services/_scripts/external-volumes/setup
+++ b/system-tests/services/_scripts/external-volumes/setup
@@ -1,6 +1,21 @@
 #!/bin/bash
 
-# create app with extenal volumes
+if [ -z "$REGION" ]; then
+  echo "Error: Please specify the REGION environment variable"
+  exit 1
+fi
+
+if [ -z "$ACCESS_KEY_ID" ]; then
+  echo "Error: Please specify the ACCESS_KEY_ID environment variable"
+  exit 1
+fi
+
+if [ -z "$SECRET_ACCESS_KEY" ]; then
+  echo "Error: Please specify the SECRET_ACCESS_KEY environment variable"
+  exit 1
+fi
+
+# create app with external volumes
 cat <<EOF | dcos marathon app add
 {
   "id": "/$TEST_UUID/external-volumes-single",
@@ -25,5 +40,5 @@ cat <<EOF | dcos marathon app add
   "cpus": 0.1,
   "cmd": "echo TEST_OUTPUT_$TEST_UUID >> \$MESOS_SANDBOX/data/foo; cat \$MESOS_SANDBOX/data/foo; while true; do sleep 10; done;",
   "mem": 16
-} 
+}
 EOF
