chore: drop system tests driver

diff --git a/scripts/utils/tests-functions b/scripts/utils/tests-functions
--- a/scripts/utils/tests-functions
+++ b/scripts/utils/tests-functions
@@ -3,107 +3,6 @@
 set -e
 [ -n "${DEBUG}" ] && set -x
 
-# This script is a temporary solution to run the integration tests in a <= 1.GB
-# memory environment and with support for retries per test file. We should
-# replace it with a test runner in the future, please see it more as a proof of
-# concept
-
-## Configuration
-#####################################################################
-
-# Search string passed to `find`
-# Values: String
-SEARCH='*'
-
-# Run headed Chrome instead of headless
-# Values: anything :)
-CYPRESS_HEADED=
-
-# Don't close headed Chrome after spec finishes
-# Values: anything :)
-CYPRESS_NO_EXIT=
-
-# Maximum number of retries
-# Values: n ∈ ℕ
-RETRIES=${RETRIES:-3}
-
-# Stop if file failed $RETRIES times? (turn this off, if you want
-# to test all tests locally but something keeps failing)
-# Values: 0, 1
-STOP_ON_FAIL=${STOP_ON_FAIL:-1}
-
-# Suppresses Cypress output on failures
-# Values: 0, 1
-SUPPRESS_OUTPUT=${SUPPRESS_OUTPUT:-0}
-
-CLEANUP_TESTS=${CLEANUP_TESTS:-0}
-
-PROXY_PORT=${PROXY_PORT:-4200}
-PROXY_PID=0
-
-PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
-CYPRESS_FOLDER="cypress"
-TESTS_FOLDER="tests"
-
-PLUGINS_PATH=${PLUGINS_PATH:-''}
-
-while getopts 's:hnr:?' flag; do
-  case "${flag}" in
-    s) SEARCH=${OPTARG:-'*'} ;;
-    h) CYPRESS_HEADED="true" ;;
-    n) CYPRESS_NO_EXIT="true" ;;
-    r) RETRIES=${OPTARG} ;;
-    ?)
-      echo -e "+-------------------------------+"
-      echo -e "| DC/OS Integration test runner |"
-      echo -e "+-------------------------------+\n"
-      echo -e "Don't forget running npm run build:assets first!\n\n"
-      echo -e "Usage: \n"
-      echo -e "\tnpm run test:integration -- [-s <FILE_NAME>] [-hn] [-r <RETRIES>]\n"
-      echo -e "Options:\n"
-        printf "  %-17s %-30s \n" "-s <TestFileName>" "Run single Test File. All files if omitted"
-        printf "  %-17s %-30s \n" "-h" "Run Chrome in Headed mode"
-        printf "  %-17s %-30s \n" "-n" "Don't close Chrome after tests are finished"
-        printf "  %-17s %-30s \n" "-r <NUM_RETRIES>" "Number of retries, 3 by default"
-        printf "  %-17s %-30s \n" "-?" "Prints this help"
-        echo ""
-      exit 0 ;;
-  esac
-done
-
-## Configuration
-#####################################################################
-
-# Search string passed to `find`
-# Values: String
-SEARCH=${1:-'*'}
-
-# Maximum number of retries
-# Values: n ∈ ℕ
-RETRIES=${RETRIES:-3}
-
-# Stop if file failed $RETRIES times? (turn this off, if you want
-# to test all tests locally but something keeps failing)
-# Values: 0, 1
-STOP_ON_FAIL=${STOP_ON_FAIL:-1}
-
-# Suppresses Cypress output on failures
-# Values: 0, 1
-SUPPRESS_OUTPUT=${SUPPRESS_OUTPUT:-0}
-
-CLEANUP_TESTS=${CLEANUP_TESTS:-0}
-
-PROXY_PORT=${PROXY_PORT:-4200}
-PROXY_PID=0
-
-PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )/../" && pwd )"
-CYPRESS_FOLDER="cypress"
-TESTS_FOLDER="tests"
-
-PLUGINS_PATH=${PLUGINS_PATH:-''}
-
-
-
 ## Functions
 #####################################################################
 
@@ -112,11 +11,36 @@ PLUGINS_PATH=${PLUGINS_PATH:-''}
 # from callee:
 # FILE: file to test
 # OUTPUT_PATH: Directory where results are saved (e.g. "some/path/to/Testfile-cy.js-1")
-function executeCypress {
-  npm run --silent cypress -- \
+function executeCypress() {
+  RECORD_VIDEO=${RECORD_VIDEO:-'true'}
+
+  if [ -n "${CLUSTER_URL}" ]; then
+    CYPRESS_ENV="CLUSTER_URL=\"${CLUSTER_URL}\""
+  fi
+
+  if [ -n "${CLUSTER_AUTH_TOKEN}" ]; then
+    CYPRESS_ENV="${CYPRESS_ENV},CLUSTER_AUTH_TOKEN=\"${CLUSTER_AUTH_TOKEN}\""
+  fi
+
+  if [ -n "${CLUSTER_AUTH_INFO}" ]; then
+    CYPRESS_ENV="${CYPRESS_ENV},CLUSTER_AUTH_INFO=\"${CLUSTER_AUTH_INFO}\""
+  fi
+
+  if [ -n "${TEST_UUID}" ]; then
+    CYPRESS_ENV="${CYPRESS_ENV},TEST_UUID=\"${TEST_UUID}\""
+  fi
+
+  if [ -n "${CYPRESS_ENV}" ]; then
+    CYPRESS_ENV="--env $CYPRESS_ENV"
+  fi
+
+  npx cypress run \
+    ${CYPRESS_HEADED:+"--headed"} \
+    ${CYPRESS_NO_EXIT:+"--no-exit"} \
     --spec "${FILE}" \
-    --config "screenshotsFolder=${OUTPUT_PATH}/screenshots,videosFolder=${OUTPUT_PATH}/videos" \
+    --config "screenshotsFolder=${OUTPUT_PATH}/screenshots,video=${RECORD_VIDEO},videosFolder=${OUTPUT_PATH}/videos,integrationFolder=${TESTS_FOLDER},supportFile=${TESTS_FOLDER}/_support,fixturesFolder=${TESTS_FOLDER}/_fixtures" \
     --reporter junit \
+    ${CYPRESS_ENV:-""} \
     --reporter-options "mochaFile=${OUTPUT_PATH}/result.xml"
 }
 
@@ -124,22 +48,41 @@ function executeCypress {
 #
 # From callee:
 # RELATIVE_PATH: stripped down output from find command (e.g. "pages/Testfile-cy.js")
-function runTestFile {
+function runTestFile() {
   echo ""
   echo "==> Running Tests for ./${TESTS_FOLDER}/$RELATIVE_PATH"
   local RUN=0
   local EXIT_CODE=1
   while [ $EXIT_CODE -ne 0 ] && [ $RUN -lt $RETRIES ]; do
-    RUN=$((RUN+1))
+    RUN=$((RUN + 1))
     local OUTPUT_PATH="${PROJECT_ROOT}/${CYPRESS_FOLDER}/${RELATIVE_PATH}-${RUN}"
+    # Record video only on the 3rd run, videos are heavy
+    local RECORD_VIDEO=$([ "$RUN" == 3 ] && echo "true" || echo "false")
 
+    if [ -f "$(dirname "${PROJECT_ROOT}/${TESTS_FOLDER}/${RELATIVE_PATH}")/_scripts/setup" ]; then
+      echo "==> Running setup script"
+      TEST_UUID=${TEST_UUID} $(dirname "${PROJECT_ROOT}/${TESTS_FOLDER}/${RELATIVE_PATH}")/_scripts/setup
+    fi
+
+    # TODO: env vars for cypress
     echo "===> Executing Cypress (${RUN}/${RETRIES})"
-    CYOUT="$(FILE="${PROJECT_ROOT}/tests/${RELATIVE_PATH}" RUN=${RUN} OUTPUT_PATH=${OUTPUT_PATH} executeCypress)"
+    CYOUT="$(FILE="${PROJECT_ROOT}/${TESTS_FOLDER}/${RELATIVE_PATH}" \
+      RUN=${RUN} \
+      OUTPUT_PATH="${OUTPUT_PATH}" \
+      RECORD_VIDEO=${RECORD_VIDEO} \
+      executeCypress)"
     EXIT_CODE=$?
 
+    if [ -f "$(dirname "${PROJECT_ROOT}/${TESTS_FOLDER}/${RELATIVE_PATH}")/_scripts/teardown" ]; then
+      echo "==> Running teardown script"
+      TEST_UUID=${TEST_UUID} $(dirname "${PROJECT_ROOT}/${TESTS_FOLDER}/${RELATIVE_PATH}")/_scripts/teardown
+    fi
+
     if [ $EXIT_CODE -eq 0 ]; then
+      report "$RELATIVE_PATH" "success"
       echo "====> Successfully finished tests for ${RELATIVE_PATH}"
     else
+      report "$RELATIVE_PATH" "failure"
       echo "====> Failures in tests for ${RELATIVE_PATH}"
       [ $SUPPRESS_OUTPUT -eq 0 ] && echo "${CYOUT}"
     fi
@@ -159,7 +102,7 @@ function runTestFile {
 
 # copies tests from plugins folder into project
 # this is necessary because Cypress doesnt allows external files to be tested…
-function setup_plugins {
+function setup_plugins() {
   if [ -n "${PLUGINS_PATH}" ]; then
     echo "==> Setup external plugins…"
     rsync -aH "${PROJECT_ROOT}/${PLUGINS_PATH}/${TESTS_FOLDER}/" "${PROJECT_ROOT}/${TESTS_FOLDER}/"
@@ -170,7 +113,7 @@ function setup_plugins {
 }
 
 # removes copied plugins files…
-function teardown_plugins {
+function teardown_plugins() {
   if [ -n "${PLUGINS_PATH}" ]; then
     if [ "${CLEANUP_TESTS}" -eq 0 ]; then
       echo ""
@@ -188,7 +131,7 @@ function teardown_plugins {
 }
 
 # merges results from cypress runs into one file
-function teardown_merge {
+function teardown_merge() {
   if [ "$(find "${PROJECT_ROOT}/${CYPRESS_FOLDER}/" -type f -name result.xml | wc -l)" -ne 0 ]; then
     echo "==> Merging results from ./${CYPRESS_FOLDER}/*/result.xml into ./${CYPRESS_FOLDER}/results.xml…"
     junit-merge --out "${PROJECT_ROOT}/${CYPRESS_FOLDER}/results.xml" $(find "${PROJECT_ROOT}/${CYPRESS_FOLDER}/" -type f -name result.xml)
@@ -198,14 +141,14 @@ function teardown_merge {
   fi
 }
 
-function teardown_proxy {
+function teardown_proxy() {
   echo "==> Killing Proxy…"
   kill $PROXY_PID
   echo "===> done."
 }
 
 # sets up everything
-function setup {
+function setup_integration() {
   echo ""
   echo "=> Setup"
 
@@ -218,10 +161,20 @@ function setup {
     echo "==> ERROR: no dist folder! forgot npm run build?"
     exit 1
   fi
-  echo "==> Starting http-server, serving files from ./dist…"
-  http-server -sp "${PROXY_PORT}" "${PROJECT_ROOT}/dist"&
-  PROXY_PID=$!
-  echo "===> done (PID: ${PROXY_PID})."
+
+  if [ -n "${CLUSTER_URL}" ]; then
+    echo "==> Starting http-server, proxying ${CLUSTER_URL}, serving files from ./dist…"
+    npx http-server -sp "${PROXY_PORT}" --proxy "${CLUSTER_URL}" --proxy-secure=false "${PROJECT_ROOT}/dist" &
+    PROXY_PID=$!
+    CLUSTER_URL_PROXIED="${CLUSTER_URL}"
+    CLUSTER_URL="http://127.0.0.1:${PROXY_PORT}"
+    echo "===> done (PID: ${PROXY_PID})."
+  else
+    echo "==> Starting http-server, serving files from ./dist…"
+    npx http-server -sp "${PROXY_PORT}" "${PROJECT_ROOT}/dist" &
+    PROXY_PID=$!
+    echo "===> done (PID: ${PROXY_PID})."
+  fi
 
   ## Setup plugins if configured
   if [ -n "${PLUGINS_PATH}" ]; then
@@ -237,7 +190,7 @@ function setup {
 }
 
 # tears down everything…
-function teardown {
+function teardown_integration() {
   echo ""
   echo "=> Teardown"
   teardown_proxy
@@ -246,24 +199,36 @@ function teardown {
   echo "=> Bye."
 }
 
+# reports to data dog if flag is set
+# $1 should be the file path
+# $2 should be "success" or "failure"
+function report() {
+  if [ "$REPORT" = true ]; then
+    file=$(basename $1)
+    filename=${file%-cy.js}
+
+    dogapi metric send "dcos_ui.$2" 1 --type 'count' --tags "distribution:$DISTRIBUTION,branch:$BRANCH,testfile:$filename"
+  fi
+}
+
 # finds the files and runs the tests
-function run_tests {
+function run_tests_integration() {
+  run_tests_one_by_one
+}
+
+function run_all_tests() {
+  echo ""
+  echo "=> Running All Tests"
+  FILE="$PROJECT_ROOT/${TESTS_FOLDER}/**/*-cy.js" \
+    OUTPUT_PATH="${PROJECT_ROOT}/${CYPRESS_FOLDER}/all" \
+    executeCypress || exit 1
+}
+
+function run_tests_one_by_one() {
   echo ""
   echo "=> Running Tests"
-  find "$PROJECT_ROOT/${TESTS_FOLDER}" -type f -name "${SEARCH}-cy.js" -print | \
-    while read FOUND_FILE
-    do
+  find "$PROJECT_ROOT/${TESTS_FOLDER}" -type f -name "${SEARCH}-cy.js" -print |
+    while read FOUND_FILE; do
       RELATIVE_PATH="$(echo "${FOUND_FILE}" | sed s+${PROJECT_ROOT}/${TESTS_FOLDER}/++)" runTestFile || exit 1
     done
 }
-
-## Programm
-#####################################################################
-
-
-
-source "$SCRIPT_PATH/utils/tests-functions"
-
-setup_integration
-trap teardown_integration EXIT
-run_tests_integration
