refactor(ci): refactor upload-build script

diff --git a/scripts/ci/utils/upload-build b/scripts/ci/utils/upload-build
--- a/scripts/ci/utils/upload-build
+++ b/scripts/ci/utils/upload-build
@@ -1,41 +1,71 @@
 #!/bin/bash
-set -ex
 
-# configuration
+# This script is intended to be called by the ci scripts, please dont
+# execute it directly.
+
+## Configuration
+#####################################################################
+
+SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"
+
+PROJECT_ROOT="$( cd "${SCRIPT_PATH}/../../../" && pwd )"
+
 AWS_BUCKET='downloads.mesosphere.io'
-BUCKET_PATH='dcos-ui'
-BRANCH_NAME=${BRANCH_NAME:-'master'}
-PKG_VERSION=$(git tag -l --contains HEAD)
 
-if [[ $PKG_VERSION ]]
-then
-  PKG_VERSION="-$PKG_VERSION"
+BUCKET_PATH='dcos-ui'
+
+FORCE_UPLOAD=${FORCE_UPLOAD:-0}
+
+PKG_TARGET=${PKG_TARGET:-""}
+
+PKG_NAME=${PKG_NAME:-""}
+
+PKG_VERSION=${PKG_VERSION:-""}
+
+PKG_META=${PKG_META:-""}
+
+## Check Params
+#####################################################################
+
+if [ -z "${PKG_TARGET}" ] || [ -z "${PKG_NAME}" ] || [ -z "${PKG_VERSION}" ]; then
+  echo "Cant update DC/OS repo without given \$PKG_TARGET, \$PKG_NAME and \$PKG_VERSION!"
+  exit 1
 fi
 
-PKG_BRANCH=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')
+if [ ! -f "${PROJECT_ROOT}/release.tar.gz" ]; then
+  echo "./release.tar.gz not found, stopping here"
+  exit 1
+fi
 
-# ex. dcos-ui-v1.12.0-rc.11.tar.gz
-RELEASE_NAME="dcos-ui${PKG_VERSION}.tar.gz"
+## Building release name
+#####################################################################
 
-# tar dist
-cd "dist"
-tar czf "../$RELEASE_NAME" .
-cd ..
+RELEASE_NAME="${PKG_TARGET}+${PKG_NAME}-${PKG_VERSION}"
+[ -n "${PKG_META}" ] && RELEASE_NAME="${RELEASE_NAME}+${PKG_META}"
+RELEASE_NAME="${RELEASE_NAME}.tar.gz"
 
-BUILD_SHA=$(shasum ${RELEASE_NAME} | cut -d " " -f1)
 ENCODED_RELEASE_NAME=$(echo ${RELEASE_NAME} | sed "s/\+/\%2B/g")
-DOWNLOAD_URL=$(echo "https://${AWS_BUCKET}/${BUCKET_PATH}/${ENCODED_RELEASE_NAME}")
+
+## Write buildinfo.json
+#####################################################################
 
 # cat config to artifact file
-cat <<EOF > buildinfo.json
+cat <<EOF > "${PROJECT_ROOT}/buildinfo.json"
 {
   "single_source": {
     "kind": "url_extract",
-    "url": "${DOWNLOAD_URL}",
-    "sha1": "${BUILD_SHA}"
+    "url": "$(echo "https://${AWS_BUCKET}/${BUCKET_PATH}/${ENCODED_RELEASE_NAME}")",
+    "sha1": "$(shasum "${PROJECT_ROOT}/release.tar.gz" | cut -d " " -f1)"
   }
 }
 EOF
 
-# upload
-aws s3 cp $RELEASE_NAME s3://$AWS_BUCKET/$BUCKET_PATH/$RELEASE_NAME
+## Upload tarball
+#####################################################################
+
+if [ ${FORCE_UPLOAD} -eq 0 ] && [ -n "$(aws s3 ls "s3://$AWS_BUCKET/$BUCKET_PATH/$RELEASE_NAME" | wc -l)" ]; then
+  echo "This release was already uploaded, stopping here"
+  exit 1
+fi
+
+aws s3 cp "${PROJECT_ROOT}/release.tar.gz" "s3://$AWS_BUCKET/$BUCKET_PATH/$RELEASE_NAME"
