feat(ci): automatically create release with standard-version
Closes DCOS-21921

diff --git a/scripts/ci/release-version b/scripts/ci/release-version
--- a/scripts/ci/release-version
+++ b/scripts/ci/release-version
@@ -11,7 +11,7 @@
 # Also make sure to `npm run build` before!
 #
 # Use this from project root:
-# npm run build && tar czf "release.tar.gz" dist && BRANCH_NAME=$(git branch | grep \* | cut -d' ' -f2) GIT_COMMIT=$(git rev-parse HEAD) CREATE_RELEASE=1 ./scripts/ci/release-version
+# npm run build && tar czf "release.tar.gz" dist && BRANCH_NAME=$(git branch | grep \* | cut -d' ' -f2) GIT_COMMIT=$(git rev-parse HEAD) CREATE_RELEASE=1 PUSH_MASTER=1 ./scripts/ci/release-version
 
 ## Configuration
 #####################################################################
@@ -20,12 +20,37 @@ SCRIPT_PATH="$(dirname "$0")/$(dirname "$(readlink "$0")")"
 
 PROJECT_ROOT="$( cd "${SCRIPT_PATH}/../../" && pwd )"
 
+CREATE_RELEASE=${CREATE_RELEASE:-0}
+PUSH_MASTER=${PUSH_MASTER:-0}
+
 # `master`` is fine, but if BRANCH_NAME is `release/1.11` we only want `1.11`
 PKG_TARGET=$(echo ${BRANCH_NAME} | sed -E 's/([^/]*)$|./\1/g')
 PKG_NAME="dcos-ui"
 PKG_VERSION=$(python -c "import sys, json; \
   pkg = json.load(open('$PROJECT_ROOT/package.json')); \
   sys.stdout.write(str(pkg['version']));")
+
+## Create & Push Release
+#####################################################################
+
+if [ ${CREATE_RELEASE} -eq 0 ]; then
+  echo "No release, no Bump!"
+  exit 1
+fi
+
+npx standard-version
+if [ $? -ne 0 ]; then
+  echo "Cannot create release, stopping here."
+  exit 1
+fi
+
+if [ ${PUSH_MASTER} -eq 1 ]; then
+  git push --follow-tags origin master
+  if [ $? -ne 0 ]; then
+    echo "Failed to push new release to master, stopping here"
+    exit 1
+  fi
+fi
 
 ## Create Assets & Generate Upload Data
 #####################################################################
